Repository MasoniteFramework/core, pull requests merged in 2018-05, with the labels that each got.

#104 fixed postgres and sqlite password byte issue
  masonite/snippets/auth/controllers/RegisterController.py
  setup.py
Labels: bug

#116 Add the tinker command
  masonite/commands/TinkerCommand.py
  masonite/providers/AppProvider.py
Labels: enhancement, requires discussion

#117 Add routes command
  masonite/commands/RoutesCommand.py
  masonite/providers/AppProvider.py
  setup.py
Labels: enhancement

#119 Add optional code reloading into the masonite serve command
  masonite/commands/ServeCommand.py
  setup.py
Labels: enhancement

#126 Fix exception view title and response exception handling
  masonite/exceptions.py
  masonite/providers/StartResponseProvider.py
  masonite/snippets/exception.html
  tests/providers/test_start_response.py
Labels: bug, can-merge

#127 Add delete to session drivers
  masonite/contracts/SessionContract.py
  masonite/drivers/SessionCookieDriver.py
  masonite/drivers/SessionMemoryDriver.py
  tests/test_session.py
Labels: enhancement

#131 added class tests for views and wildcard view composers
  masonite/view.py
  resources/templates/mail/welcome.html
  tests/test_view.py
Labels: enhancement, next-minor

#137 Change tests to classes
  masonite/stacktrace.py
  masonite/testsuite/TestSuite.py
  tests/broadcasts/test_sockets.py
  tests/providers/test_route_provider.py
  tests/providers/test_start_response.py
  tests/queues/test_async_driver.py
  tests/test_app.py
  tests/test_auth.py
  tests/test_cache.py
  tests/test_compile_sass.py
  tests/test_container.py
  tests/test_controllers.py
  tests/test_cookie_signing.py
  tests/test_csrf.py
  tests/test_exception.py
  tests/test_extends.py
  tests/test_helpers_urls.py
  tests/test_hook.py
  tests/test_imports.py
  tests/test_mailgun_driver.py
  tests/test_managers_mail_manager.py
  tests/test_package.py
  tests/test_providers.py
  tests/test_request_routes.py
  tests/test_requests.py
  tests/test_routes.py
  tests/test_server.py
  tests/test_service_provider.py
  tests/test_session.py
  tests/test_signing.py
  tests/test_smtp_driver.py
  tests/test_stacktrace.py
  tests/test_testsuite.py
  tests/test_upload_manager.py
  tests/test_validator.py
Labels: next-minor

#122 Change request variables
  masonite/request.py
  tests/test_extends.py
  tests/test_requests.py
Labels: can-merge, enhancement, next-major
