Repository MasoniteFramework/core, pull requests merged in 2018-09, with the labels that each got.

#255 Remove container resolving
  app/http/controllers/ControllerTest.py
  app/http/middleware/AddAttributeMiddleware.py
  app/http/middleware/MiddlewareTest.py
  app/http/middleware/TestHttpMiddleware.py
  app/http/middleware/TestMiddleware.py
  masonite/app.py
  masonite/drivers/BaseMailDriver.py
  masonite/drivers/BroadcastAblyDriver.py
  masonite/drivers/BroadcastPusherDriver.py
  masonite/drivers/CacheDiskDriver.py
  masonite/drivers/QueueAsyncDriver.py
  masonite/drivers/SessionCookieDriver.py
  masonite/drivers/SessionMemoryDriver.py
  masonite/drivers/UploadDiskDriver.py
  masonite/drivers/UploadS3Driver.py
  masonite/helpers/routes.py
  masonite/hook.py
  masonite/middleware/CsrfMiddleware.py
  masonite/middleware/JsonResponseMiddleware.py
  masonite/providers/AppProvider.py
  masonite/providers/BroadcastProvider.py
  masonite/providers/CacheProvider.py
  masonite/providers/HelpersProvider.py
  masonite/providers/MailProvider.py
  masonite/providers/QueueProvider.py
  masonite/providers/RouteProvider.py
  masonite/providers/SessionProvider.py
  masonite/providers/StartResponseProvider.py
  masonite/providers/StatusCodeProvider.py
  masonite/providers/UploadProvider.py
  masonite/providers/WhitenoiseProvider.py
  middleware/CsrfMiddleware.py
  tests/middleware/test_csrf_middleware.py
  tests/providers/test_route_provider.py
  tests/providers/test_start_response.py
  tests/providers/test_statuscode_provider.py
  tests/test_app.py
  tests/test_container.py
  tests/test_csrf.py
  tests/test_mailgun_driver.py
  tests/test_managers_mail_manager.py
  tests/test_service_provider.py
  tests/test_upload_manager.py
Labels: beta-1, next-major

#263 Fix auth classes
  masonite/snippets/auth/controllers/HomeController.py
  masonite/snippets/auth/controllers/LoginController.py
  masonite/snippets/auth/controllers/RegisterController.py
Labels: beta-1

#273 removed need for any |safe filters
  masonite/helpers/view_helpers.py
  masonite/middleware/CsrfMiddleware.py
  middleware/CsrfMiddleware.py
  resources/templates/csrf_field.html
  tests/test_csrf.py
Labels: beta-2, next-major

#287 Update routeprovider
  masonite/helpers/routes.py
  masonite/providers/RouteProvider.py
  tests/test_app.py
Labels: next-minor

#271 added view tests
  masonite/view.py
  resources/templates/admin_test.html
  tests/test_view.py
Labels: next-minor

#252 Next Minor - 2.0.20
  .coveragerc
  .travis.yml
  CONTRIBUTING.md
  masonite/app.py
  masonite/auth/Sign.py
  masonite/contracts/__init__.py
  masonite/contracts/managers/BroadcastManagerContract.py
  masonite/contracts/managers/CacheManagerContract.py
  masonite/contracts/managers/MailManagerContract.py
  masonite/contracts/managers/QueueManagerContract.py
  masonite/contracts/managers/SessionManagerContract.py
  masonite/contracts/managers/UploadManagerContract.py
  masonite/drivers/MailSmtpDriver.py
  masonite/facades/__pycache__/Auth.cpython-36.pyc
  masonite/info.py
  masonite/managers/BroadcastManager.py
  masonite/managers/CacheManager.py
  masonite/managers/MailManager.py
  masonite/managers/QueueManager.py
  masonite/managers/SessionManager.py
  masonite/managers/UploadManager.py
  masonite/view.py
  resources/templates/admin_test.html
  setup.py
  tests/test_managers_mail_manager.py
  tests/test_signing.py
  tests/test_view.py
Labels: next-minor

#318 HTTP status mapping int for str
  masonite/exceptions.py
  masonite/helpers/status.py
  masonite/request.py
  tests/test_requests.py
Labels: next-major

#296 Remove the redundant coveralls reporting
  .travis.yml
Labels: next-minor

#328 added hotfix for multi select values
  masonite/helpers/__init__.py
  masonite/helpers/misc.py
  masonite/info.py
  masonite/request.py
  tests/helpers/test_dot_notation.py
  tests/test_requests.py
Labels: bug, hot-fix

#308 added several methods to the service provider class
  masonite/helpers/__init__.py
  masonite/helpers/misc.py
  masonite/provider.py
  tests/test_service_provider.py
Labels: beta-2, next-major

#245 added view based scaffolding
  .travis.yml
  MANIFEST.in
  masonite/commands/BaseScaffoldCommand.py
  masonite/commands/CommandCommand.py
  masonite/commands/ControllerCommand.py
  masonite/commands/JobCommand.py
  masonite/commands/ModelCommand.py
  masonite/commands/ProviderCommand.py
  masonite/commands/ValidatorCommand.py
  masonite/commands/__init__.py
  masonite/helpers/filesystem.py
  masonite/snippets/scaffold/command.html
  masonite/snippets/scaffold/controller.html
  masonite/snippets/scaffold/controller_resource.html
  masonite/snippets/scaffold/job.html
  masonite/snippets/scaffold/model.html
  masonite/snippets/scaffold/provider.html
  masonite/snippets/scaffold/validator.html
Labels: beta-2, next-major

#366 added match routes
  app/http/controllers/ControllerTest.py
  masonite/exceptions.py
  masonite/helpers/routes.py
  masonite/providers/RouteProvider.py
  masonite/routes.py
  masonite/testing/MockRoute.py
  tests/providers/test_route_provider.py
  tests/test_routes.py
Labels: beta-2

#388 request redirections now set the status code
  masonite/helpers/routes.py
  masonite/request.py
  tests/test_requests.py
Labels: beta-2

#369 Update Auth snippets to use Bootstrap 4
  masonite/snippets/auth/templates/auth/base.html
  masonite/snippets/auth/templates/auth/home.html
  masonite/snippets/auth/templates/auth/login.html
  masonite/snippets/auth/templates/auth/register.html
Labels: beta-2
