Repository MasoniteFramework/core, pull requests merged in 2018-02, with the labels that each got.

#16 Fixes issues with uploading and redirecting
  masonite/drivers/UploadDiskDriver.py
  masonite/request.py
  setup.py
  tests/test_requests.py
Labels: bug

#23 Fix setup.py and requirements.txt
  requirements.txt
  setup.py
Labels: PEP

#25 Add template caching support #19
  .gitignore
  bootstrap/cache/.gitkeep
  config/application.py
  config/cache.py
  masonite/drivers/CacheDiskDriver.py
  masonite/drivers/__init__.py
  masonite/managers/CacheManager.py
  masonite/providers/CacheProvider.py
  masonite/providers/RouteProvider.py
  masonite/providers/ViewProvider.py
  masonite/view.py
  resources/templates/test_cache.html
  routes/api.py
  tests/test_cache.py
  tests/test_view.py
Labels: enhancement
