Repository MasoniteFramework/core, pull requests merged in 2018-07, with the labels that each got.

#209 Adds url from controller method to request class
  masonite/request.py
  tests/test_requests.py
Labels: enhancement, next-minor

#207 added is_named_route method
  masonite/request.py
  tests/test_requests.py
Labels: enhancement, next-minor

#206 Add a way to "pop" off variables from the input. #197
  masonite/request.py
  tests/test_requests.py
Labels: enhancement, next-minor

#201 Next Minor
  masonite/helpers/routes.py
  masonite/info.py
  masonite/providers/HelpersProvider.py
  masonite/request.py
  tests/test_requests.py
Labels: next-release

#213 Next Minor
  masonite/helpers/view_helpers.py
  masonite/info.py
  masonite/providers/HelpersProvider.py
  masonite/request.py
  masonite/routes.py
  masonite/view.py
  resources/templates/filter.html
  tests/test_requests.py
  tests/test_routes.py
  tests/test_view.py
Labels: next-minor, next-release

#216 specifically specified .env location
  masonite/environment.py
  masonite/info.py
Labels: hot-fix

#215 Add better validation
  masonite/helpers/__init__.py
  masonite/helpers/validator.py
  masonite/validator.py
  tests/test_validator.py
Labels: next-minor

#222 fixed route Nonetype error for route groups
  masonite/info.py
  masonite/routes.py
  tests/test_routes.py
Labels: hot-fix
