Repository MasoniteFramework/core, pull requests merged in 2019-01, with the labels that each got.

#514 fixed issue with view render method
  masonite/view.py
  tests/middleware/test_csrf_middleware.py
  tests/test_csrf.py
  tests/test_view.py
Labels: hotfix

#520 Add in container
  masonite/app.py
  tests/test_container.py
Labels: enhancement, next-minor

#544 fixes issue where a json null could throw an exception
  masonite/request.py
  tests/test_requests.py
Labels: bug

#529 fix delete method when body length is 0
  masonite/routes.py
Labels: bug
